inherit_from:
  - .rubocop_airbnb.yml

# Rails 用に最適化
Rails:
  Enabled: true

# 文字数上限
LineLength:
  Max: 100

# スキャン適用外のフォルダ、ファイル
AllCops:
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'node_modules/**/*'
    - 'bin/*'
    - '**/Gemfile'
    - 'vendor/**/*'
    - '.git/**/*'
