services:
  app:
    build:
      context: docker/app
      dockerfile: Dockerfile
      target: ${TARGET:-development}
      args:
        - RUBY_VERSION=${RUBY_VERSION:-3.2.2}
        - RAILS_VERSION=${RAILS_VERSION:-7.0.4.3}
        - BUCKET=${BUCKET:-photos}
    volumes:
      - .:/workspace
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER?}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD?}
    working_dir: /workspace
    ports:
      - 3000:3000
      - 1234:1234
      - 9000:9000
      - 9001:9001
    tty: true
    depends_on:
      db:
        condition: service_healthy

  db:
    build:
      context: docker/db
      dockerfile: Dockerfile
      args:
        - PGSQL_VERSION=${PGSQL_VERSION:-15.2}
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
